import { Inter } from "next/font/google";
import "./globals.css";
import BurgerMenu from "@/components/BurgerMenu/BurgerMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BurgerMenu/>
        {children}
      </body>
    </html>
  );
}
